version: '3.1'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: psagrera/jenkins_master:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/jenkins/jenkins_home:/var/jenkins_home
        networks:
            - testing
        privileged: true
    robot:
        container_name: robot
        image: psagrera/vixia
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/jenkins/jenkins_home:/var/jenkins_home
        stdin_open: true
        tty: true
        networks:
            - testing

networks:
    testing:
        external: true


